if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
	set_property(GLOBAL PROPERTY USE_FOLDERS ON)
endif()

function(add_project_to_group target folder)
	if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		set(SOURCE_GROUP_DELIMITER "/")
		set(last_dir "")
		set(files "")

		get_target_property(sources ${target} SOURCES)

		foreach(file ${sources})
			file(RELATIVE_PATH relative_file "${PROJECT_SOURCE_DIR}" ${file})
			get_filename_component(dir "${relative_file}" PATH)
			if(NOT "${dir}" STREQUAL "${last_dir}")
				if(files)
					source_group("${last_dir}" FILES ${files})
				endif()
				set(files "")
			endif()
			set(files ${files} ${file})
			set(last_dir "${dir}")
		endforeach()

		if(files)
			source_group("${last_dir}" FILES ${files})
		endif()
		set_target_properties(${target} PROPERTIES FOLDER ${folder})
  endif()
endfunction()
